config/routes.rb
Rails.application.routes.draw do
    get 'cities_movies/index'

    get 'cities/index'

    get 'movies/index'

    get 'welcome/index'

    resources :movies do
        collection { post :import }
    end
    resources :cities
    resources :cities_movies

    root 'movies#index'

end

app/models/cities_movie.rb
class CitiesMovie < ActiveRecord::Base
  belongs_to :movie
  belongs_to :city
end

app/models/city.rb
class City < ActiveRecord::Base
    has_many :cities_movies
    has_many :movies, :through => :cities_movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :cities_movies
    has_many :cities, :through => :cities_movies

    # choosing which row is going in which column in the database and translating the columns names to english
    MAPPING = {
        "titre" => "title",
        "distrib" => "distributor",
        "nb de sem" => "weeks",
        "nb copies" => "number_of_copies",
        "entrées" => "spectators_per_week",
        "cumulFrance" => "total_spectators",
        "Taux de hte sat." => "satisfaction_rate"
        # didnt had the column realease_date it's not in the file uploading file
        #just had it here when you'll have it and dont forget to had it under as well.
    }

    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        # starting values reading from line 3 since line 2 is an empty line
        (3..spreadsheet.last_row).each do |i|
            row = Hash[[header, spreadsheet.row(i)].transpose]
            # Convert the keys from the csv/xls to match the database column names
            row.keys.each { |k| row[ MAPPING[k] ] = row.delete(k) if MAPPING[k] }

            # check if the title already exists in the database to override its previous values
            m = Movie.find_or_initialize_by(title: row[ 'title' ])
            m.distributor = row[ 'distributor' ]
            m.weeks = row[ 'weeks' ]
            m.number_of_copies = row[ 'number_of_copies' ]
            m.spectators_per_week = row[ 'spectators_per_week' ]
            m.total_spectators = row[ 'total_spectators' ]
            m.satisfaction_rate = row[ 'satisfaction_rate' ].to_f
            m.save

            #add the city "France" to the movie created
            CitiesMovie.create(city_id: 1, movie_id: m.id)
        end
    end

    def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then Roo::CSV.new(file.path)
        when ".xls" then Roo::Excel.new(file.path)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.original_filename}"
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    before_action :set_city, only: [:show]

    def index
         @cities = City.all
         respond_to do |format|
             format.html # index.html.erb
             format.json { render :json => @cities }
         end
    end

    def show
        @cities = City.where(movie_id: @movie)
    end

    private

    def set_city
        @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(
      :id,
      :city
      )
    end
end

app/controllers/cities_movies_controller.rb
class CitiesMoviesController < ApplicationController
    before_action :set_movies, :set_cities
        
    def index
    end

    def show
        @movies = Movie.where(city_id: @city)
    end

    private

    def set_movies
        @movies = Movie.find(params[:id])
    end

    def set_cities
        @cities = City.find(params[:id])
    end

    def params
        params.require(:cities_movies).permit(
        :city_id,
        :movie_id
        )
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movie, only: [:show]

    def index
        @movies = Movie.all
        respond_to do |format|
            format.html # index.html.erb
            format.json { render :json => @movies }
        end
    end

    def new
        @movie = Movie.new
    end

    def show
    end

    def import
        Movie.import(params[:file])
        # redirection to the index after the import
        redirect_to action: :index
    end


    private

    def set_movie
        @movie = Movie.find(params[:id])
    end

    def film_params
        params.require(:movie).permit(
        :id,
        :title,
        :distributor,
        :release_date,
        :weeks,
        :number_of_copies,
        :spectators_per_week,
        :total_spectators,
        :satisfaction_rate
        )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/cities_movies_helper.rb
module CitiesMoviesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<div class="panel panel-primary">

    <div class="panel-heading">CITIES</div>

    <table class="table table-striped grey">
        <% @cities.each do |city| %>
        <td>
            <%= link_to city.city, city %>
        </td>
        <% end %>
    </table>
    </div>
</div>

<%= link_to 'Back to Movies', movies_path %>

app/views/cities/show.html.erb
<p>
    <strong>City:</strong>
    <%= @city.city %>
</p>

<p>
    <strong>Movies:</strong>
</p>

<table class="table">
    <tr class="success">
<td>
    <% @city.movies.each do |movie|%>
    <li> <%= movie.title %> </li>
    <% end %>
</td>
</tr>
</table>

<%= link_to 'Back', cities_path %>

app/views/cities_movies/index.html.erb
<h1>CitiesMovies#index</h1>
<p>Find me in app/views/cities_movies/index.html.erb</p>

app/views/cities_movies/show.html.erb
<p>
    <strong>City:</strong>
    <%= @city.city %>
</p>

<p>
    <strong>Movies:</strong>
    <%= @movie.title %>
</p>

<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcranT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div class="panel panel-success">
    <div class="panel-heading">MOVIES</div>
    <!-- Table -->
    <table class="table table-striped grey">
        <tr>
            <th>Movies</th>
            <th>Distributor</th>
            <th>Spectators This Week</th>
        </tr>
        <% @movies.each do |movie| %>
        <tr>
            <td><%= link_to movie.title, movie, :class => "btn btn-default glyphicon glyphicon-film" %></td>
            <td><%= movie.distributor %></td>
            <td><%= movie.spectators_per_week %></td>
        </tr>
        <% end %>
    </div>
</table>
<div class="panel-footer">IMPORT FILES</div>
<!-- <h3>Import Movies</h3> -->

        <%= form_tag import_movies_path, multipart: true do %>

        <%= file_field_tag :file %>
        <%= submit_tag "Import" %>
        <% end %>
</div>

</html>

app/views/movies/show.html.erb
<p>
  <strong>Movie's Title:</strong>
    <%= @movie.title %>
</p>

<p>
  <strong>Distributor:</strong>
    <%= @movie.distributor %>
</p>

<p>
  <strong>Release Date:</strong>
    <%= @movie.release_date %>
</p>

<p>
  <strong>Weeks in Theater:</strong>
    <%= @movie.weeks %>
</p>

<p>
  <strong>Number of Copies:</strong>
    <%= @movie.number_of_copies %>
</p>

<p>
  <strong>Spectators Per Week:</strong>
    <%= @movie.spectators_per_week%>
</p>

<p>
  <strong>Total of Spectators:</strong>
    <%= @movie.total_spectators %>
</p>

<p>
  <strong>Satisfaction Rate:</strong>
    <%= (@movie.satisfaction_rate * 100).round %>%
</p>

<p>
  <strong>Cities:</strong>
    <% @movie.cities.each do |city|%>
    <li> <%= city.city %> </li>
    <% end %>
</p>

<%= link_to 'Back', movies_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p> Test welcome OK </p>